
username = input('Назовите себя: ')
title = input('Назовите вашу заметку: ')
content = input('Введите текст заметки: ')
created_date = input('Введите дату начала в формате дд-мм-гг: ')
issue_date = input('Введите дату окончания в формате дд-мм-гг: ')
print('Ваше имя: ', username )
print('Название заметки: ', title )
print('Содержание заметки: ', content)
print('Дата создания заметки: ', created_date)
print('Дата окончания действия заметки: ', issue_date)
